name: Demo Workflow       # The Workflow name
on: [push]                    # The Trigger (Event)

jobs:                         # Container for all jobs
  build:             # A specific Job ID
    runs-on: ubuntu-latest    # The Runner (Environment)
    steps:                    # List of Steps in this job
      - run: ech "Compiling the application!"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Shipping It" 
